AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS API Gateway with a Lambda Integration
Parameters:
  LambdaFuncName:
    Type: String
    Default: "pythonTest"
  LambdaRuntime:
    Type: String
    Default: "python3.6"
  LambdaHandler:
    Type: String
    Default: "index.lambda_handler"
  LambdaMemory:
    Type: Number
    Default: 128
  LambdaTimeout:
    Type: Number
    Default: 40
  TableName:
    Type: String
    Default: 'lambdalogs'
    Description: (Required) The name of the new DynamoDB table you want to create and save to. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'
Resources:
  FunctionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - dynamodb.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - 
      Path: /
    Type: AWS::IAM::Role
  LambdaFunc:
    Properties:
      CodeUri: ./lambda-deploy.zip
      Layers:
        - arn:aws:lambda:us-east-1:432853048830:layer:bt3103-dependency-packages:4
      Description: Statistical Learning by 1d4
      FunctionName:
        Ref: "LambdaFuncName"
      Events:
        ExecuteFunc:
          Properties:
            Method: ANY
            Path: /{proxy+}
          Type: Api
      Handler:
        Ref: "LambdaHandler"
      MemorySize:
        Ref: "LambdaMemory"
      Role:
        Fn::GetAtt:
          - FunctionRole
          - Arn
      Runtime:
        Ref: "LambdaRuntime"
      Timeout:
        Ref: "LambdaTimeout"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: 
              Ref: TableName
      Environment:
        Variables:
          TABLE_NAME: 
            Ref: TableName 
    Type: AWS::Serverless::Function
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        Ref: TableName
      AttributeDefinitions:
        - AttributeName: logId
          AttributeType: S
      KeySchema:
        - AttributeName: logId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST




